(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t);if(e){var r=e.getAttribute("data-src");e.setAttribute("src",r)}};ldv=function(t){var e=document.querySelector(t);if(e){var r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.load()}};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un148');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/forum-romanum_1200-1025.jpg');
var a='data-src';var e=document.querySelector('.un149');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_7_1200-550.jpg':'images/albert_rieger_7_1200-275.jpg');
var a='data-src';var e=document.querySelector('.un150');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_8_1200-550.jpg':'images/albert_rieger_8_1200-275.jpg');
var a='data-src';var e=document.querySelector('.un151');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_3_1200-550.jpg':'images/albert_rieger_3_1200-275.jpg');
var a='data-src';var e=document.querySelector('.un152');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_6_1200-550.jpg':'images/albert_rieger_6_1200-275.jpg');
var a='data-src';var e=document.querySelector('.un153');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_1_1200-550.jpg':'images/albert_rieger_1_1200-275.jpg');
var a='data-src';var e=document.querySelector('.un154');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_5_1200-550.jpg':'images/albert_rieger_5_1200-275.jpg');
var a='data-src';var e=document.querySelector('.un155');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_2_1200-550.jpg':'images/albert_rieger_2_1200-275.jpg');
var a='data-src';var e=document.querySelector('.un156');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_4_1200-550.jpg':'images/albert_rieger_4_1200-275.jpg');
var e=document.querySelector('.un143');e.setAttribute('src','images/panorama-di-fiume-c1860-1025.jpg');
var e=document.querySelector('.un145');e.setAttribute('src','images/albertrieger-422.jpg');
var e=document.querySelector('.un146');e.setAttribute('src','images/wasserfall-in-gerbige-900-819.jpg');
var e=document.querySelector('.un147');e.setAttribute('src','images/landscape1869-102x115cm-980.jpg');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un148');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/forum-romanum_1200-1640.jpg':'images/forum-romanum_1200-820.jpg');
var a='data-src';var e=document.querySelector('.un149');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_7_1200-440.jpg':'images/albert_rieger_7_1200-220.jpg');
var a='data-src';var e=document.querySelector('.un150');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_8_1200-440.jpg':'images/albert_rieger_8_1200-220-1.jpg');
var a='data-src';var e=document.querySelector('.un151');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_3_1200-440.jpg':'images/albert_rieger_3_1200-220.jpg');
var a='data-src';var e=document.querySelector('.un152');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_6_1200-440.jpg':'images/albert_rieger_6_1200-220.jpg');
var a='data-src';var e=document.querySelector('.un153');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_1_1200-440.jpg':'images/albert_rieger_1_1200-220.jpg');
var a='data-src';var e=document.querySelector('.un154');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_5_1200-440.jpg':'images/albert_rieger_5_1200-220.jpg');
var a='data-src';var e=document.querySelector('.un155');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_2_1200-440.jpg':'images/albert_rieger_2_1200-220.jpg');
var a='data-src';var e=document.querySelector('.un156');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_4_1200-440.jpg':'images/albert_rieger_4_1200-220.jpg');
var e=document.querySelector('.un143');e.setAttribute('src',(dpi>1)?'images/panorama-di-fiume-c1860-1640.jpg':'images/panorama-di-fiume-c1860-820.jpg');
var e=document.querySelector('.un145');e.setAttribute('src','images/albertrieger-338.jpg');
var e=document.querySelector('.un146');e.setAttribute('src','images/wasserfall-in-gerbige-900-655.jpg');
var e=document.querySelector('.un147');e.setAttribute('src','images/landscape1869-102x115cm-784.jpg');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un148');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/forum-romanum_1200-1312.jpg':'images/forum-romanum_1200-656.jpg');
var a='data-src';var e=document.querySelector('.un149');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_7_1200-352.jpg':'images/albert_rieger_7_1200-176.jpg');
var a='data-src';var e=document.querySelector('.un150');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_8_1200-352.jpg':'images/albert_rieger_8_1200-176.jpg');
var a='data-src';var e=document.querySelector('.un151');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_3_1200-352.jpg':'images/albert_rieger_3_1200-176.jpg');
var a='data-src';var e=document.querySelector('.un152');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_6_1200-352.jpg':'images/albert_rieger_6_1200-176.jpg');
var a='data-src';var e=document.querySelector('.un153');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_1_1200-352.jpg':'images/albert_rieger_1_1200-176.jpg');
var a='data-src';var e=document.querySelector('.un154');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_5_1200-352.jpg':'images/albert_rieger_5_1200-176.jpg');
var a='data-src';var e=document.querySelector('.un155');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_2_1200-352.jpg':'images/albert_rieger_2_1200-176.jpg');
var a='data-src';var e=document.querySelector('.un156');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_4_1200-352.jpg':'images/albert_rieger_4_1200-176.jpg');
var e=document.querySelector('.un143');e.setAttribute('src',(dpi>1)?'images/panorama-di-fiume-c1860-1312.jpg':'images/panorama-di-fiume-c1860-656.jpg');
var e=document.querySelector('.un145');e.setAttribute('src',(dpi>1)?'images/albertrieger-540.jpg':'images/albertrieger-270.jpg');
var e=document.querySelector('.un146');e.setAttribute('src','images/wasserfall-in-gerbige-900-524.jpg');
var e=document.querySelector('.un147');e.setAttribute('src',(dpi>1)?'images/landscape1869-102x115cm-1256.jpg':'images/landscape1869-102x115cm-628.jpg');}else{var a='data-src';var e=document.querySelector('.un148');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/forum-romanum_1200-546.jpg':'images/forum-romanum_1200-273.jpg');
var a='data-src';var e=document.querySelector('.un149');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_7_1200-146.jpg':'images/albert_rieger_7_1200-73.jpg');
var a='data-src';var e=document.querySelector('.un150');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_8_1200-146.jpg':'images/albert_rieger_8_1200-73.jpg');
var a='data-src';var e=document.querySelector('.un151');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_3_1200-146.jpg':'images/albert_rieger_3_1200-73.jpg');
var a='data-src';var e=document.querySelector('.un152');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_6_1200-146.jpg':'images/albert_rieger_6_1200-73.jpg');
var a='data-src';var e=document.querySelector('.un153');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_1_1200-146.jpg':'images/albert_rieger_1_1200-73.jpg');
var a='data-src';var e=document.querySelector('.un154');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_5_1200-146.jpg':'images/albert_rieger_5_1200-73.jpg');
var a='data-src';var e=document.querySelector('.un155');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_2_1200-146.jpg':'images/albert_rieger_2_1200-73.jpg');
var a='data-src';var e=document.querySelector('.un156');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/albert_rieger_4_1200-146.jpg':'images/albert_rieger_4_1200-73.jpg');
var e=document.querySelector('.un143');e.setAttribute('src',(dpi>1)?'images/panorama-di-fiume-c1860-546.jpg':'images/panorama-di-fiume-c1860-273.jpg');
var e=document.querySelector('.un145');e.setAttribute('src',(dpi>1)?'images/albertrieger-226.jpg':'images/albertrieger-113.jpg');
var e=document.querySelector('.un146');e.setAttribute('src',(dpi>1)?'images/wasserfall-in-gerbige-900-436.jpg':'images/wasserfall-in-gerbige-900-218.jpg');
var e=document.querySelector('.un147');e.setAttribute('src',(dpi>1)?'images/landscape1869-102x115cm-522.jpg':'images/landscape1869-102x115cm-261.jpg');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var n=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));n||(n=1);var r=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];if(!r)return;var l=/chrome/i.test(navigator.userAgent);o=l?r.getBoundingClientRect().top*n+pageYOffset:(r.getBoundingClientRect().top+pageYOffset)*n}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var a=pageYOffset,i=null;requestAnimationFrame(function e(t){i||(i=t);var n=t-i;scrollTo(0,a<o?(o-a)*n/400+a:a-(a-o)*n/400),n<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
$('.un203').mouseenter(function() { $.loadImages('images/albert_rieger_7_1200-1200.jpg', function() { }) });
$('.un203').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un203-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/albert_rieger_7_1200-1200.jpg'; } } });
$('.un205').mouseenter(function() { $.loadImages('images/albert_rieger_8_1200-851.jpg', function() { }) });
$('.un205').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un205-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/albert_rieger_8_1200-851.jpg'; } } });
$('.un207').mouseenter(function() { $.loadImages('images/albert_rieger_3_1200-858.jpg', function() { }) });
$('.un207').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un207-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/albert_rieger_3_1200-858.jpg'; } } });
$('.un209').mouseenter(function() { $.loadImages('images/albert_rieger_6_1200-1200.jpg', function() { }) });
$('.un209').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un209-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/albert_rieger_6_1200-1200.jpg'; } } });
$('.un211').mouseenter(function() { $.loadImages('images/albert_rieger_1_1200-1200.jpg', function() { }) });
$('.un211').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un211-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/albert_rieger_1_1200-1200.jpg'; } } });
$('.un213').mouseenter(function() { $.loadImages('images/albert_rieger_5_1200-1200.jpg', function() { }) });
$('.un213').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un213-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/albert_rieger_5_1200-1200.jpg'; } } });
$('.un215').mouseenter(function() { $.loadImages('images/albert_rieger_2_1200-1200.jpg', function() { }) });
$('.un215').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un215-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/albert_rieger_2_1200-1200.jpg'; } } });
$('.un217').mouseenter(function() { $.loadImages('images/albert_rieger_4_1200-1200.jpg', function() { }) });
$('.un217').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un217-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/albert_rieger_4_1200-1200.jpg'; } } });
wl=new woolite();
wl.init();
wl.addAnimation($('.un142'), "1.00s", "0.00s", 1, 100);
wl.addAnimation($('.un144'), "1.00s", "0.00s", 1, 100);
wl.start();
if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"0px"===window.getComputedStyle(document.body).getPropertyValue("min-width")&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un202 source');ldsrcset('.un204 source');ldsrcset('.un206 source');ldsrcset('.un208 source');ldsrcset('.un210 source');ldsrcset('.un212 source');ldsrcset('.un214 source');ldsrcset('.un216 source');ldsrcset('.un218 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}